sonar.projectKey=Javier-Sinuka_ion-core-
sonar.organization=javier-sinuka

sonar.projectName=ion-core
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# Analizar lo que realmente se compila/genera extract.sh
sonar.sources=src,inc,scripts

# C/C++: usar la base de compilación generada por build-wrapper
sonar.cfamily.compile-commands=build-wrapper-output/compile_commands.json

# CLAVE: permitir que Sonar analice src/ e inc/ aunque estén en .gitignore
sonar.scm.exclusions.disabled=true

# Evitar artefactos y dependencias descargadas
sonar.exclusions=\
build/**,\
build-wrapper-output/**,\
.sonar/**,\
.git/**,\
.github/**,\
tmp/**,\
bin/**,\
lib/**,\
man/**,\
**/*.o,\
**/*.a,\
**/*.so,\
**/*.log,\
**/__pycache__/**,\
**/build-wrapper-dump.json
