sonar.projectKey=Javier-Sinuka_ion-core-
sonar.organization=javier-sinuka

sonar.projectName=ion-core
sonar.projectVersion=1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

# ION-CORE es C/C++, por eso usamos la compilation database generada por Build Wrapper.
sonar.cfamily.compile-commands=build-wrapper-output/compile_commands.json

# Evitar analizar artefactos, cachés, outputs y contenido temporal.
sonar.exclusions=\
build/**,\
build-wrapper-output/**,\
.sonar/**,\
.git/**,\
.github/**,\
tmp/**,\
lib/obj/**,\
bin/**,\
man/**,\
**/*.o,\
**/*.a,\
**/*.so,\
**/*.log,\
**/__pycache__/**

